[package]
name = "racket-rust-ffi-experiment"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "foo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
